version: 2

models:
  - name: stg_online_retail
    description: "Cleaned and typed staging model for Online Retail data"
    columns:
      - name: invoice_id
        description: "Unique invoice identifier"
        tests:
          - not_null
      - name: product_id
        description: "Stock code of the product"
        tests:
          - not_null
      - name: revenue
        description: "Calculated as quantity * price"
